apiVersion: v1
kind: Service
metadata:
  name: ng-dashboard-app
  labels:
    app: ng-dashboard-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31001
  selector:
    app: ng-dashboard-app